import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { UserRole } from '@prisma/client'
import { verifyApiToken, ApiUser } from '@/lib/api-auth'

export interface SimpleAuthUser {
  id: string
  email: string
  name?: string | null
  role: UserRole
  phone?: string | null
  branchId?: string | null
}

/**
 * Securely authenticate API requests. In development, support a dev-key
 * to return a mock super admin. In production, require a valid
 * bearer token generated by the API; verify it and look up the
 * corresponding active user. Returns null if authentication fails.
 */
export async function simpleAuth(request: NextRequest): Promise<SimpleAuthUser | null> {
  try {
    // Development bypass with dev-key
    const apiKey = request.headers.get('x-api-key') || new URL(request.url).searchParams.get('apiKey')
    if (process.env.NODE_ENV === 'development' && apiKey === 'dev-key') {
      return {
        id: 'dev-user',
        email: 'dev@example.com',
        name: 'Development User',
        role: UserRole.SUPER_ADMIN,
        phone: null,
        branchId: null
      }
    }
    // Require a valid bearer token in production
    const authHeader = request.headers.get('authorization')
    if (authHeader && authHeader.startsWith('Bearer ')) {
      const token = authHeader.substring(7)
      const decoded: ApiUser | null = verifyApiToken(token)
      if (decoded) {
        const user = await db.user.findFirst({
          where: { id: decoded.id, isActive: true }
        })
        if (user) {
          return {
            id: user.id,
            email: user.email,
            name: user.name,
            role: user.role,
            phone: user.phone,
            branchId: user.branchId
          }
        }
      }
    }
    return null
  } catch (error) {
    console.error('simpleAuth error:', error)
    return null
  }
}

export function hasRequiredRole(user: SimpleAuthUser | null, requiredRoles: UserRole[]): boolean {
  if (!user) return false
  return requiredRoles.includes(user.role)
}

export async function requireSimpleAuth(request: NextRequest, requiredRoles?: UserRole[]) {
  const user = await simpleAuth(request)
  if (!user) {
    return {
      error: new Response(
        JSON.stringify({ error: 'Authentication required' }),
        { status: 401, headers: { 'Content-Type': 'application/json' } }
      )
    }
  }
  if (requiredRoles && !hasRequiredRole(user, requiredRoles)) {
    return {
      error: new Response(
        JSON.stringify({ error: 'Insufficient permissions' }),
        { status: 403, headers: { 'Content-Type': 'application/json' } }
      )
    }
  }
  return { user }
}
